### ISSUE TITLE
Problem with slashes in episode title

### ISSUE THREAD

**Issue by schwammtaucher** [akhilrex/podgrab#106]
Hello there,
at first I want to say thank you for the good ideas and the very nice implementation.

 - Installation Type: Docker
 - Have you tried using the latest docker image / code base.  yes

I am very interested in der feature, that episode names are used as filenames. Testing with a german audio podcast I found out, that slashes in episode titles cause a minor problem in the filename. 

Title in RSS: König Klops und die kleine Seiltänzerin (1/2): Ein dicker König, schwer verliebt
Resulting Filename: 2)-Ein-dicker-Koenig,-schwer-verliebt.mp3

As you can see, the slash results in splitting the string and the second Part is used as the filename. The named podcast uses a lot of slashes, because there are published different parts of stories following this scheme "1/3" (part one of three).
By the way: I realy like to see, that the german "mutated vowels" are translated in usual letters. 

Here is the URL of the RSS:
https://www.ohrenbaer.de/podcast/podcast.feed.podcast.xml

Thnaky you very much for your work!

**Comment by schwammtaucher** [comment]
This is associated to an existing pull request, which I sadly spottet after posting. :-(
Sorry.
"Better filename sanitization #77"

**Comment by akhilrex** [comment]
I have fixed this. Please rebuild your container with the latest image once the current build is complete.

**Comment by schwammtaucher** [comment]
Hi there and thank you very much for your reply.
I have rebuilt the container with the image created a few hours ago.

The problem is still there.

So I checked the fileService.go in the current sourcecode. There is still 
return sanitize.Name(original) 
instead of 
return sanitize.BaseName(original)  

Did the merge of #77 work correct?

Thank you very much again and best wishes!

**Comment by akhilrex** [comment]
I have made the change in the sanitize.Name function only. Let me check
again.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Seems to be working for me. You will have to download the older episodes again for it to come into effect.

![image](https://user-images.githubusercontent.com/576190/120585284-18a72600-c44f-11eb-93f4-896f551e53ad.png)
