### ISSUE TITLE
Items show up as "Added 296 years ago"

### ISSUE THREAD

**Issue by Forceu** [akhilrex/podgrab#2]
Thank you for your project, it looks quite promising!

I just tried added this podcast RSS: https://www1.wdr.de/mediathek/audio/wdr2/wdr2-zugabe/zugabe-podcast-100.podcast

However all items show up as "296 years ago" and in the overview "Last Episode : Jan 1 0001"

**Comment by akhilrex** [comment]
Thanks for opening this issue. I have fixed the issue with time formatting and committed the code. The image should get built in the next 20 mins. You will just have to update the container image and delete and re-add the podcast.

**Comment by Forceu** [comment]
Thanks! For some reason the Docker image is still not updated, even though it says that it was last built 14 hours ago. By building the image on my own with the provided Dockerfile it works though.

**Comment by akhilrex** [comment]
GitHub actions must be having an issue. I will force a new build.

Thanks and Regards

Akhil Gupta
