### ISSUE TITLE
Podcasts missing thumbnail icon

### ISSUE THREAD

**Issue by ksurl** [akhilrex/podgrab#37]
looks like all podcasts on the relay.fm site and other squarespace based sites are missing the icon on the home page. for example add a podcast like The Test Drivers. it has the default podgrab art. If you click on the podcast, individual episodes have the icon picture. Other podcasts are fine (serial, soundcloud based feed, other hosts, etc)

**Comment by akhilrex** [comment]
Thanks for pointing this out. This has been fixed. The image is getting built as I write this message. Just recreate the container and re-add the podcast and you should be good to go.

**Comment by ksurl** [comment]
I'm still getting the same problem after updating and making sure to empty browser cache. screenshot: 
![image](https://user-images.githubusercontent.com/1371562/106918015-af402200-66bd-11eb-9d63-40db3e3857e7.png)

**Comment by akhilrex** [comment]
You will have to delete and add the podcast again.

Thanks and Regards

Akhil Gupta

**Comment by ksurl** [comment]
will it detect existing episodes that are downloaded?

**Comment by akhilrex** [comment]
It will.

You can do this. Backup the podcast MP3 folder. Delete the podcast. Put the
folder back. Add podcast. It will not redownload episodes already present.

Thanks and Regards

Akhil Gupta
